language: android
sudo: false
jdk: oraclejdk8
branches:
  except:
  - /^v[0-9\.]+/
env:
  global:
  - GRADLE_OPTS="-Xmx4g"
android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.2
  - android-24
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go get github.com/aktau/github-release
script:
  - ./gradlew -s clean assemble
before_deploy:
  - ./gradlew assembleRelease -Pandroid.injected.signing.store.file=.credentials/key.jks -Pandroid.injected.signing.store.password=$STORE_PASSWORD -Pandroid.injected.signing.key.alias=migrate -Pandroid.injected.signing.key.password=$STORE_PASSWORD
deploy:
  - github-release release --user dankideacentral --repo migrate-app --tag v$(cat .version) --name $(cat .version) --description "Built by your friendly neighbourhood Travis CI" --pre-release
  - github-release upload  --user dankideacentral --repo migrate-app  --tag v$(cat .version) --name "release-v$(cat .version).apk" --file "app/build/outputs/apk/app-release.apk"
