language: android
sudo: false
jdk: oraclejdk8
branches:
  except:
  - /^v[0-9\.]+/
env:
  global:
  - GRADLE_OPTS="-Xmx4g"
android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.2
  - android-24
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go get github.com/aktau/github-release
after_success:
  - github-release release --user dankideacentral --repo migrate-app --tag v$(cat .version) --name $(cat .version) --description "Built by Travis CI" --pre-release
  - github-release upload  --user dankideacentral --repo migrate-app  --tag v$(cat .version) --name "release.apk" --file "app/build/outputs/apk/app-release-unsigned.apk"
script:
  - ./gradlew -s clean assemble
  - ./gradlew build assembleRelease
